# Change these first
owner: leafle # Your GitHub username
repo: mki-api-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Meraki API Docs
    url: https://developer.cisco.com/meraki/api-v1/
  - name: Meraki API Org Show
    url: https://api.meraki.com/api/v1/organizations/43483
    headers:
    - "X-Cisco-Meraki-API-Key: $MKI_API_KEY"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /mki-api-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Meraki API Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a simple status page for the Meraki API.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
